include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    require_trailing_commas: error
    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning

linter:
  rules:
    require_trailing_commas: true

    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    prefer_single_quotes: true
    sort_constructors_first: true
    use_super_parameters: true
    avoid_print: true
    unnecessary_lambdas: true
    avoid_unnecessary_containers: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: false
    annotate_overrides: true
    prefer_final_fields: true
    prefer_final_locals: true
